version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
